# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
# This workflow is managed by gh actions-lock.
name: Scorecards supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '23 4 * * 1'

permissions:
  actions: read

jobs:
  analysis:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@da2c748aad55c1a1dcba00b60fe4a35017bc6540
    permissions:
      contents: read
      security-events: write
      id-token: write
    secrets: inherit
